import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.MaterialsEngineeringPowderMetallurgyLemmaCanonicalLaneLean.CrystallographyLattice
import HautevilleHouse.MaterialsEngineeringPowderMetallurgyLemmaCanonicalLaneLean.PhaseDiagram
import HautevilleHouse.MaterialsEngineeringPowderMetallurgyLemmaCanonicalLaneLean.ElasticityFracture
import HautevilleHouse.MaterialsEngineeringPowderMetallurgyLemmaCanonicalLaneLean.SinteringKinetics
import HautevilleHouse.MaterialsEngineeringPowderMetallurgyLemmaCanonicalLaneLean.PowderCharacterization

namespace HautevilleHouse
namespace MaterialsEngineeringPowderMetallurgyLemmaCanonicalLaneLean

def ConstrainedPowderMetallurgyClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_powder_metallurgy_endgame (A : AdmissibleClass) :
    ConstrainedPowderMetallurgyClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end MaterialsEngineeringPowderMetallurgyLemmaCanonicalLaneLean
end HautevilleHouse
